### ISSUE TITLE
Wrong Config-Parameters in default noterc

### ISSUE THREAD

**Issue by Nudin** [TLINDEN/note#1]
The default noterc lists the following options:

    binary::MaxNoteByte  = 4096          # max bytes per note entry
    binary::MaxTimeByte  = 64            # max bytes for the date

After they didn't worked for me, I looked at the source, the right names are different:

    binary::max_note  = 4096
    binary::max_time  = 64

You should ether fix the source or the noterc-documentation.

**Comment by TLINDEN** [comment]
Thanks for reporting!
