### ISSUE TITLE
Create tags for releases versions

### ISSUE THREAD

**Issue by eamanu** [TLINDEN/note#3]
Hi!

I am maintaining note package on [Debian](https://tracker.debian.org/pkg/note). 

Currently, the debian/watch file download the last version from [here](http://www.daemon.de/NOTE). But this is using a plain http. For that reason, my mentor Dmitry Bogatov <KAction@debian.org> recommend me change it to https. But daemon.com is http.

So, I open this issue to try convince you to create tags on Github, so from this way I can configure d/watch to download note from Github.

**Comment by TLINDEN** [comment]
Hi,

I'm pretty sure you Debian people have an established process how to turn perl modules into packages. That is, the primary source is CPAN: https://metacpan.org/pod/distribution/note/note.pod. It's HTTPS, correctly versioned and there's even an API for tool based access.

However, https://www.daemon.de/ works as well. But CPAN is always the reference.


best,
Tom

**Comment by eamanu** [comment]
hmmm yesterday, I intent to do uscan -dd to https but does not work :-(. I will try again.  But, cpan could be a great option.

**Comment by eamanu** [comment]
I have this error:

https://www.daemon.de/idisk/Apps/note/ failed: 500 Can't connect to www.daemon.de:443 (SSL connect attempt failed error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol)

**Comment by eamanu** [comment]
Using cpan work correctly. 

Please, consider create tags on Github. That can be useful for Github users. 

Thanks.

**Comment by TLINDEN** [comment]
Added tag.  Your SSL-Problem is unrelated to note (maybe my ssl version is too old, but I don't care really).
