### ISSUE TITLE
Problems on Installation

### ISSUE THREAD

**Issue by eamanu** [TLINDEN/note#7]
Hi!, 

When I run `perl Makefile.PL` (following the install instruction) this get the next error:

```
Warning: the following files are missing in your kit:
	META.json
	META.yml
```

**Comment by eamanu** [comment]
But, looking on CPAN webpage but that files exist.

**Comment by TLINDEN** [comment]
Yes, this is intended. The installable tarball must be downloaded from CPAN. Here on github I only maintain the sources. The Meta-Files are not source, they are generated when I create the dist tarball. This is how perl modules work.

**Comment by eamanu** [comment]
Great thanks!
